//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShopThoiTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietBans = new HashSet<ChiTietBan>();
            this.ChiTietNhaps = new HashSet<ChiTietNhap>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string ChatLieu { get; set; }
        public string MoTa { get; set; }
        public string MaLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBan> ChiTietBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhap> ChiTietNhaps { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhapKho NhapKho { get; set; }
        public virtual GioHang GioHang { get; set; }
    }
}
