//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLShopThoiTrang.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string userID { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
        public string userRole { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual QuanLy QuanLy { get; set; }
    }
}
